In [ ]:
string = "Peter picked a pail of picked peppers"
string

'Peter picked a pail of picked peppers'

In [ ]:
import tensorflow as tf

# display tf version and test if GPU is active
tf.__version__,tf.test.gpu_device_name()


('2.6.0', '/device:GPU:0')

## Download a File from a url 

In [ ]:
# import keras module
from tensorflow import keras

In [ ]:
ds = "auto-mpg.data"
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"
dataset_path = tf.keras.utils.get_file(ds,url)
dataset_path

40960/30286 [========================================] - 0s 3us/step


'/root/.keras/datasets/auto-mpg.data'

In [ ]:
# import the pandas library
import pandas as pd


In [ ]:
cols = ["MPG","Cylinders","Displacement","Horsepower","Weight","Acceleration","Model Year","Origin"]

raw_dataset = pd.read_csv(dataset_path, names=cols,na_values="?",comment="\t",sep=" ",skipinitialspace=True)

In [ ]:
raw_dataset.tail()

MPG  Cylinders  Displacement  ...  Acceleration  Model Year  Origin
393  27.0          4         140.0  ...          15.6          82       1
394  44.0          4          97.0  ...          24.6          82       2
395  32.0          4         135.0  ...          11.6          82       1
396  28.0          4         120.0  ...          18.6          82       1
397  31.0          4         119.0  ...          19.4          82       1

[5 rows x 8 columns]

In [ ]:
#Creating a copy

data = raw_dataset.copy()

In [ ]:
# verify contents by displaying some data
data.tail()

MPG  Cylinders  Displacement  ...  Acceleration  Model Year  Origin
393  27.0          4         140.0  ...          15.6          82       1
394  44.0          4          97.0  ...          24.6          82       2
395  32.0          4         135.0  ...          11.6          82       1
396  28.0          4         120.0  ...          18.6          82       1
397  31.0          4         119.0  ...          19.4          82       1

[5 rows x 8 columns]

# Tensors

In [ ]:
# Scalars(0D Tensors)
import numpy as np


In [ ]:
#Create numpy scalar 9

scalar = np.array(9)
scalar

array(9)

In [ ]:
# signal it's rank

print(str(scalar.ndim) + "D")

0D


# Vectors(1D Tensors)

In [ ]:
# create numpy vector [0,1,0,0,0,0]
vector = np.array([0,1,0,0,0,0])
vector

array([0, 1, 0, 0, 0, 0])

In [ ]:
# signal it's rank
print(str(vector.ndim) + "D")

1D


# Matrices (2D Tensors)

In [ ]:
# Create a numpy matrix
matrix = np.array(
    [
     [0,1,0,0,0,0],
     [0,0,1,0,0,0],
     [0,0,0,1,0,0],
     [0,0,0,0,1,0],
     [0,0,0,0,0,1]
    ]
)
matrix

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [ ]:
# signal it's rank
print(str(matrix.ndim) + "D")

2D


# 3D Matrices (3D Tensors)

In [ ]:
# Create a 3D tensor

D3 = np.array([[[0,1,2]],[[3,4,5]],[[6,7,8]]])
D3

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [ ]:
# signal it's rank

print(str(D3.ndim) + "D")

3D


# Key Attributes of Tensors

In [ ]:
#Shape of 3D matrices
D3.shape

(3, 1, 3)

In [ ]:
# Shape of our 2d matrix

matrix.shape

(5, 6)

In [ ]:
# shape of our vector
vector.shape

(6,)

In [ ]:
#Shape of our scalar

scalar.shape

()

# Datatypes of the tensors

In [ ]:
# dtype of tensors

print(scalar.dtype)
print(vector.dtype)
print(matrix.dtype)
print(D3.dtype)

int64
int64
int64
int64


# Input Pipelines 

In [ ]:
# Creating a simple tensorflow tensor

X = tf.range(5)
X

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [ ]:
#using numpy to display values from a Tensorflow tensor

X.numpy()

array([0, 1, 2, 3, 4], dtype=int32)

In [ ]:
#Accessing individual elements from a tensor

# first element from tensor

X[0].numpy()

0

In [ ]:
# Getting the 2nd, 3rd and 4th elements from tensor
X[1:4].numpy()

array([1, 2, 3], dtype=int32)

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(X)
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [ ]:
# Iterate a tf.data.Dataset

for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


# Tensors and numpy

In [ ]:
# create a variable to hold a line break

br = "\n"

#Creating a numpy array from a Tensorflow dataset


# technique 1

ls = []

for item in dataset:
  e = item.numpy()
  ls.append(e)

np_arr = np.asarray(ls,dtype=np.float32)
print(type(np_arr))
print(np_arr,br)

<class 'numpy.ndarray'>
[0. 1. 2. 3. 4.] 



In [ ]:
# technique 2
ls = [item.numpy() for item in dataset]
np_arr = np.asarray(ls, dtype=np.float32)
print(type(np_arr))
print(np_arr,br)

<class 'numpy.ndarray'>
[0. 1. 2. 3. 4.] 



In [ ]:
#converting the numpy array back to a tensorflow dataset with the constant method

tf_arr = tf.constant(np_arr)
tf_arr

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [ ]:
# Constants are immutable. If their values need to be modified use the variable method

tf_arr = tf.Variable(np_arr)
tf_arr

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

# Chaining Transformations

In [ ]:
# Creating a tf.data.dataset and showing it's values

dataset = tf.data.Dataset.range(5)

for item in dataset:
  print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)


In [ ]:
# Using the repeat method to repeat elements in a tensor

data_rep = dataset.repeat(3)

In [ ]:
for item in data_rep:
  print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)


In [ ]:
#Chaining transformations

data_batch = dataset.repeat(3).batch(7)

In [ ]:
for item in data_batch:
  print(item)

tf.Tensor([0 1 2 3 4 0 1], shape=(7,), dtype=int64)
tf.Tensor([2 3 4 0 1 2 3], shape=(7,), dtype=int64)
tf.Tensor([4], shape=(1,), dtype=int64)


In [ ]:
# Dropping the final batch

data_drop = dataset.repeat(3).batch(7,drop_remainder=True)



In [ ]:
for item in data_drop:
  print(item)

tf.Tensor([0 1 2 3 4 0 1], shape=(7,), dtype=int64)
tf.Tensor([2 3 4 0 1 2 3], shape=(7,), dtype=int64)


In [ ]:
# Creating equal batches

data_equal = dataset.repeat(3).batch(5)


In [ ]:
for item in data_equal:
  print(item)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


# Mapping Tensors

In [ ]:
# creating a dataset

dataset = tf.data.Dataset.range(7)


In [ ]:
# repeat and batch it
data_batch = dataset.repeat(3).batch(7)

In [ ]:
# Display the batched dataset

for row in data_batch:
  print(row)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int64)
tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int64)
tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int64)


In [ ]:
# map() a function on it

data_map = data_batch.map(lambda x: x**2)

In [ ]:
# display the first batch
print()
for item in data_map.take(1):
  print(item)


tf.Tensor([ 0  1  4  9 16 25 36], shape=(7,), dtype=int64)


# Filter a tf.data.Dataset

In [ ]:
# create a dataset

dataset = tf.data.Dataset.range(7)


In [ ]:
#display the dataset
for row in dataset:
  print(row)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)


In [ ]:
# apply a filter
data_filter = dataset.filter(lambda x: x < 6 and x > 3)

In [ ]:
print()
for item in data_filter:
  print(item)


tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)


# Shuffling a Dataset

In [ ]:
# create a dataset

dataset = tf.data.Dataset.range(10).repeat(3)
print("Dataset has", len(list(dataset)) , "elements")

Dataset has 30 elements


In [ ]:
# Shuffle the data into batches of 7

ds = dataset.shuffle(buffer_size=5).batch(7)


In [ ]:
for item in ds:
  print(item)

tf.Tensor([0 1 5 3 6 7 2], shape=(7,), dtype=int64)
tf.Tensor([0 2 8 4 5 6 9], shape=(7,), dtype=int64)
tf.Tensor([3 7 9 4 2 3 8], shape=(7,), dtype=int64)
tf.Tensor([1 6 0 8 4 1 9], shape=(7,), dtype=int64)
tf.Tensor([7 5], shape=(2,), dtype=int64)


In [ ]:
#rerun to get a different shuffle

for item in ds:
  print(item)

tf.Tensor([0 3 6 7 4 9 5], shape=(7,), dtype=int64)
tf.Tensor([1 1 3 8 4 2 2], shape=(7,), dtype=int64)
tf.Tensor([7 5 0 0 2 3 8], shape=(7,), dtype=int64)
tf.Tensor([4 5 6 6 9 8 7], shape=(7,), dtype=int64)
tf.Tensor([1 9], shape=(2,), dtype=int64)


# TensorFlow Math

## Vector Tensors

In [ ]:
# Create data

v1 = np.array([0,1,4,8,16])
v2 = np.array([0,3,9,27,81])

In [ ]:
#Convert numpy arrays to tensor constants and add

conv1 = tf.constant(v1)
conv2 = tf.constant(v2)

result = tf.add(conv1,conv2)
result

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 0,  4, 13, 35, 97])>

In [ ]:
# Convert numpy arrays to tensor variable and add

varv1 = tf.Variable(v1)
varv2 = tf.Variable(v2)

result = tf.add(varv1,varv2)
result

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 0,  4, 13, 35, 97])>

In [ ]:
# Subtract tensor variables

result = tf.subtract(varv2,varv1)
result

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 0,  2,  5, 19, 65])>

In [ ]:
# Mix constants and variables

result = tf.add(conv1,varv2)
result

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 0,  4, 13, 35, 97])>

In [ ]:
# Test for equivalency

result = tf.equal(varv1,varv2)
result

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True, False, False, False, False])>

In [ ]:
# Multiply tensor constants

result = tf.multiply(conv1,conv2)
result

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([   0,    3,   36,  216, 1296])>

In [ ]:
# Divide a tensor by a value

result = tf.divide(conv2,3)
result

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 0.,  1.,  3.,  9., 27.])>

# Matrix Tensors

In [ ]:
# create data

m1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
m2 = np.array([[1,0,0],[0,1,0],[0,0,1]])

m1.shape,m2.shape

((3, 3), (3, 3))

In [ ]:
# Convert numpy matrices to tensors and add

conm1 = tf.constant(m1)
conm2 = tf.constant(m2)

result = tf.add(conm1,conm1)
result

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])>

In [ ]:
# Test for equivalency

result = tf.equal(conm1,conm2)
result

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

# tf.data.Dataset Tensors

In [ ]:
# Create a dataset

m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Convert the dataset into a tf.data.Dataset

dataset = tf.data.Dataset.from_tensor_slices(m)
dataset

<TensorSliceDataset shapes: (4,), types: tf.int64>

In [ ]:
# Display the tensors

for t in dataset:
  print(t)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int64)
tf.Tensor([ 9 10 11 12], shape=(4,), dtype=int64)


In [ ]:
# Transform tensor values

squared_data = dataset.map(lambda x: x**2)

In [ ]:
# display tensors

for item in squared_data:
  print(item)

tf.Tensor([ 1  4  9 16], shape=(4,), dtype=int64)
tf.Tensor([25 36 49 64], shape=(4,), dtype=int64)
tf.Tensor([ 81 100 121 144], shape=(4,), dtype=int64)
